// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izbhxheyvzukylhcckqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Ymh4aGV5dnp1a3lsaGNja3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTA3MTMsImV4cCI6MjA1OTU4NjcxM30.HzV_QQERUZdlJA6X3n7mxpkcPvfSUuVk4NH4HuI8olU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);